config/routes.rb
Rails.application.routes.draw do
  get 'portfolio', to: 'pages#portfolio', as: 'portfolio'
  get 'resume', to: 'pages#resume', as: 'resume'
  root to: 'pages#welcome'

  resources :contacts, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "blufairie888@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/hobby.rb
class Hobby < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def resume
  end

  def contact
  end

  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hobby_helper.rb
module HobbyHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/contact/index.html.erb
<div class="py-3 mx-5 bg-dark text-white">
<div class="container">
<h1>Contact me</h1>
</div>
<div>

app/views/contacts/create.html.erb
<div class="container">

  <h3>Thank you for your message!</h3>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <h1>Contact Kim</h1>
  <%= form_for @contact do |f| %>
    <div class="col-md-6">
      <%= f.label :name %></br>
      <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>

      <%= f.label :email %></br>
      <%= f.text_field :email, required: true, class: "contact-form-text-area" %></br>

      <%= f.label :message %></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
            placeholder: "Tell me something..."%></br>

      <div class= "d-none">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
      </div>

      <%= f.submit 'Send Message', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPortfolio</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@100;400;700&family=Slabo+27px&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <div class="container">
  <br>
  <% flash.each do |key, message| %>
    <p class="alert alert-<%= key %>"><%= message %></p>
  <% end %>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</div>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js" integrity="sha384-SlE991lGASHoBfWbelyBPLsUlwY1GwNDJo3jSJO04KZ33K2bwfV9YBauFfnzvynJ" crossorigin="anonymous"></script>
  </body>
  <%= render "shared/footer" %>
  </div>
</html>

app/views/pages/portfolio.html.erb
<div class="py-2 mx-2">
  <h1>Portfolio</h1>
    &nbsp;
  <div class="container">
    <div class="row mx-0">
      <div class="col">
        <div class="card border-light" style="width: 18rem;">
          <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/v1648377574/TraQ_dsvble.jpg" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h5 class="card-title">TraQ</h5>
            <p class="card-text">Emergency Tracking and Response Made Simple</p>
            <a href="https://www.traq.info/" class="btn btn-primary">View Site</a>
              &nbsp;
            <div class="text-center">
              <br>
              <img src="https://img.shields.io/badge/-Ruby%20on%20Rails-CC000?logo=ruby%20on%20rails&logoColor=white&style=badge" alt="rails badge"/>
              <img src="https://img.shields.io/badge/-MySQL-4479A1?logo=MySQL&logoColor=white&style=badge" alt="MySQL badge"/>
              <img src="https://img.shields.io/badge/-Ruby-CC342D?logo=ruby&logoColor=white&style=badge" alt="ruby badge"/>
              <img src="https://img.shields.io/badge/-ngrok-1F1E37?logo=ngrok&logoColor=white&style=badge" alt="ngrok badge"/>
              <img src="https://img.shields.io/badge/-Stimulus-77E8B9?logo=stimulus&logoColor=white&style=badge" alt="Stimulus badge"/>
              <img src="https://img.shields.io/badge/-JavaScript-F7DF1E?logo=javascript&logoColor=white&style=badge" alt="JS badge"/>
              <img src="https://img.shields.io/badge/-mapbox-000000?logo=mapbox&logoColor=white&style=badge" alt="mapbox badge"/>
              <img src="https://img.shields.io/badge/-html5-E34F26?logo=mapbox&logoColor=white&style=badge" alt="HTML badge"/>
              <img src="https://img.shields.io/badge/-sass-CC6699?logo=mapbox&logoColor=white&style=badge" alt="Sass badge"/>
              <img src="https://img.shields.io/badge/-bootstrap-7952B3?logo=mapbox&logoColor=white&style=badge" alt="Bootstrap badge"/>
              <img src="https://img.shields.io/badge/-trello-0052CC?logo=mapbox&logoColor=white&style=badge" alt="Trello badge"/>
              <img src="https://img.shields.io/badge/-figma-F24E1E?logo=mapbox&logoColor=white&style=badge" alt="Figma badge"/>
              <img src="https://img.shields.io/badge/-heroku-430098?logo=mapbox&logoColor=white&style=badge" alt="Heroku badge"/>
              <img src="https://img.shields.io/badge/-github-181717?logo=mapbox&logoColor=white&style=badge" alt="Github badge"/>
            </div>
          </div>
        </div>
      </div>
    <div class="col">
        <div class="card border-light" style="width: 18rem height:18rem;">
          <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/v1648377566/13-MacBook_Pro_Mockups_zgh8vp.jpg" class="card-img-top">
          <div class="card-body text-center">
            <h5 class="card-title">Happy Tours</h5>
              <p class="card-text">Connecting You To Local Breweries</p>
              <a href="https://happy-tour-795.herokuapp.com/" class="btn btn-primary">View Site</a>
              <div>
              <br>
                <img src="https://img.shields.io/badge/-Ruby%20on%20Rails-CC000?logo=ruby%20on%20rails&logoColor=white&style=badge" alt="rails badge"/>
                <img src="https://img.shields.io/badge/-MySQL-4479A1?logo=MySQL&logoColor=white&style=badge" alt="MySQL badge"/>
                <img src="https://img.shields.io/badge/-Ruby-CC342D?logo=ruby&logoColor=white&style=badge" alt="ruby badge"/>
                <img src="https://img.shields.io/badge/-JavaScript-F7DF1E?logo=javascript&logoColor=white&style=badge" alt="JS badge"/>
                <img src="https://img.shields.io/badge/-Stimulus-77E8B9?logo=stimulus&logoColor=white&style=badge" alt="Stimulus badge"/>
                <img src="https://img.shields.io/badge/-mapbox-000000?logo=mapbox&logoColor=white&style=badge" alt="mapbox badge"/>
                <img src="https://img.shields.io/badge/-html5-E34F26?logo=mapbox&logoColor=white&style=badge" alt="HTML badge"/>
                <img src="https://img.shields.io/badge/-sass-CC6699?logo=sass&logoColor=white&style=badge" alt="Sass badge"/>
                <img src="https://img.shields.io/badge/-bootstrap-7952B3?logo=mapbox&logoColor=white&style=badge" alt="Bootstrap badge"/>
                <img src="https://img.shields.io/badge/-trello-0052CC?logo=mapbox&logoColor=white&style=badge" alt="Trello badge"/>
                <img src="https://img.shields.io/badge/-figma-F24E1E?logo=mapbox&logoColor=white&style=badge" alt="Figma badge"/>
                <img src="https://img.shields.io/badge/-heroku-430098?logo=mapbox&logoColor=white&style=badge" alt="Heroku badge"/>
                <img src="https://img.shields.io/badge/-github-181717?logo=mapbox&logoColor=white&style=badge" alt="Github badge"/>
              </div>
          </div>
        </div>
    </div>
    </div>
  </div>
&nbsp;


  <div class="container">
    <div class="row mx-0">
        <div class="col">
          <div class="card border-light" style="width: 18rem;">
            <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/v1649220024/Screen_Shot_2022-04-06_at_13.40.00_gfie4k.png" class="card-img-top" alt="...">
            <div class="card-body text-center">
              <h5 class="card-title">Simple Profile</h5>
                <p class="card-text">A profile page written in HTML and CSS</p>
                <a href="https://sleepycatfuji.github.io/Kimprofile/" class="btn btn-primary">View Site</a>
                  <div>
                  <br>
                    <img src="https://img.shields.io/badge/-html5-E34F26?logo=mapbox&logoColor=white&style=badge" alt="HTML badge"/>
                    <img src="https://img.shields.io/badge/-css3-1572B6?logo=css3&logoColor=white&style=badge" alt="Css badge"/>
                    <img src="https://img.shields.io/badge/-github-181717?logo=mapbox&logoColor=white&style=badge" alt="Github badge"/>
                  </div>
            </div>
          </div>
        </div>
    <div class="col">
      <div class="card border-light" style="width: 18rem height:18rem;">
        <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/v1649314561/Screen_Shot_2022-04-07_at_15.54.33_oydxf4.png" class="card-img-top" alt="...">
          <div class="card-body text-center">
            <h5 class="card-title">Save the Turtles</h5>
              <p class="card-text">Call to action page using Vanilla HTML and CSS</p>
              <a href="https://sleepycatfuji.github.io/turtles/" class="btn btn-primary">View Site</a>
              <div>
              <br>
                <img src="https://img.shields.io/badge/-html5-E34F26?logo=mapbox&logoColor=white&style=badge" alt="HTML badge"/>
                <img src="https://img.shields.io/badge/-css3-1572B6?logo=css3&logoColor=white&style=badge" alt="Css badge"/>
                <img src="https://img.shields.io/badge/-bootstrap-7952B3?logo=mapbox&logoColor=white&style=badge" alt="Bootstrap badge"/>
                <img src="https://img.shields.io/badge/-github-181717?logo=mapbox&logoColor=white&style=badge" alt="Github badge"/>
              </div>
          </div>
      </div>
    </div>
    </div>
  </div>
  &nbsp;


    <div class="container">
      <div class="row mx-0">
        <div class="col">
          <div class="card border-light" style="width: 18rem;">
            <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/v1649404335/Screen_Shot_2022-04-08_at_16.51.35_sxf0ce.png" class="card-img-top" alt="Nobel prize screenshot">
              <div class="card-body text-center">
                <h5 class="card-title">Nobel Prizes</h5>
                  <p class="card-text">Looping through an API containing all Nobel prize winners from 1901-2018</p>
                  <a href="https://sleepycatfuji.github.io/Nobels/" class="btn btn-primary">View Site</a>
                    <div>
                    <br>
                      <img src="https://img.shields.io/badge/-JavaScript-F7DF1E?logo=javascript&logoColor=white&style=badge" alt="JS badge"/>
                      <img src="https://img.shields.io/badge/-html5-E34F26?logo=mapbox&logoColor=white&style=badge" alt="HTML badge"/>
                      <img src="https://img.shields.io/badge/-css3-1572B6?logo=css3&logoColor=white&style=badge" alt="Css badge"/>
                      <img src="https://img.shields.io/badge/-github-181717?logo=mapbox&logoColor=white&style=badge" alt="Github badge"/>
                      </div>
              </div>
          </div>
        </div>
  <div class="col">
      <div class="card border-light" style="width: 18rem height:18rem;">
        <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/v1649653112/Screen_Shot_2022-04-11_at_12.00.54_dsbtf7.png" class="card-img-top" alt="gifys">
          <div class="card-body text-center">
            <h5 class="card-title">React Giphys</h5>
              <p class="card-text">Search for your favorite Gifs using an API. JS React famework.</p>
              <a href="https://sleepycatfuji.github.io/react-giphy/" class="btn btn-primary">View Site</a>
              <div>
              <br>
                <img src="https://img.shields.io/badge/-react-61DAFB?logo=react&logoColor=white&style=badge" alt="React badge"/>
                <img src="https://img.shields.io/badge/-JavaScript-F7DF1E?logo=javascript&logoColor=white&style=badge" alt="JS badge"/>
                <img src="https://img.shields.io/badge/-html5-E34F26?logo=mapbox&logoColor=white&style=badge" alt="HTML badge"/>
                <img src="https://img.shields.io/badge/-css3-1572B6?logo=css3&logoColor=white&style=badge" alt="Css badge"/>
                <img src="https://img.shields.io/badge/-github-181717?logo=mapbox&logoColor=white&style=badge" alt="Github badge"/>
              </div>
          </div>
      </div>
    </div>


      </div>
    </div>
</div>
  &nbsp;

app/views/pages/resume.html.erb
<div class="py-3 mx-5">
<div class="container">
<h1>Resume</h1>
<img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/s49828892/3664eebaa5764ec0b74823657680a952-0001_qfn5st.jpg">
<img src="https://asset.cloudinary.com/dqmy4wjvz/3ebc3f3089100ab8d202fd297a39039b">
<img src="https://asset.cloudinary.com/dqmy4wjvz/37a4a7a47d65791c46db370ab66b2c4f">
</div>
</div>

app/views/pages/welcome.html.erb
  <h1>Kim Methakullachat</h1>
  <p>Junior Project Manager</p>
<div class="container">
 <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner bg-dark">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/w_300,h_300,c_fill/big_profile.jpg" class="d-block">
      <div class="carousel-caption d-none d-md-block">
        <h5>My Favourite Things</h5>
        <ul>Tomatoes</ul>
        <ul>Hummus</ul>
        <ul>Summer BBQ</ul>
        <ul>Picnics</ul>
        <ul>Baking</ul>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/w_300,h_300,c_fill/TraQ_dsvble.jpg" class="d-block">
      <div class="carousel-caption d-none d-md-block">
        <h5>TraQ</h5>
        <ul>
        <li> Connects NGOs to people in time of emergency</li>
        <li>Connects people to nearby shelters and NGO</li>
        </ul>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/w_300,h_300,c_fill/20-MacBook_Pro_Mockups_oeikco.jpg" class="d-block">
      <div class="carousel-caption d-none d-md-block">
        <h5>Happy Tours</h5>
        <ul>
        <li>Connects local breweries to tourists.</li>
        <li>Connects people to local breweries.</li></>
        </ul>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/portfolio/index.html.erb
<div class="py-3 mx-5 bg-dark text-white">
<div class="container">
<h1>My Portfolio</h1>
  &nbsp;
<div class="container">
  <div class="row">
    <div class="col">
<div class="card" style="width: 18rem;">
  <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/v1648377574/TraQ_dsvble.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">TraQ</h5>
    <p class="card-text">Emergency Tracking and Response Made Simple</p>
    <a href="https://www.traq.info/" class="btn btn-primary">Visit TraQ</a>
  </div>
</div>
    </div>
    <div class="col">
<div class="card" style="width: 18rem height:18rem;">
  <img src="https://res.cloudinary.com/dqmy4wjvz/image/upload/v1648377566/13-MacBook_Pro_Mockups_zgh8vp.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Happy Tours</h5>
    <p class="card-text">Connecting You To Local Breweries</p>
    <a href="https://happy-tour-795.herokuapp.com/" class="btn btn-primary">Visit Happy Tours</a>
  </div>
</div>
    </div>
  </div>
</div>
</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Sleepycatfuji"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/kimxukim/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/duangrudee.kim/"><i class="fab fa-facebook-square"></i></a>
    <a href="https://www.linkedin.com/in/duangrudee-m"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# navbar %>
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path, class:"nav-link" %>
          </a>
          </li>
          <li class="nav-item">
            <%= link_to "Projects", portfolio_path, class:"nav-link" %>
          <li class="nav-item">
          <%= link_to "Contact", new_contact_path, class:"nav-link" %>
          </li>
        </ul>
      </div>
  </div>
  </div>
</nav>